name: "Github Release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Github Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}}
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Set version
      run: |
         cd build/libs
         mv fernflower.jar fernflower-${{ steps.get_version.outputs.VERSION }}.jar
         mv fernflower-sources.jar fernflower-${{ steps.get_version.outputs.VERSION }}-sources.jar
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/fernflower-*.jar
